apiVersion: cclab.kubeaegis.com/v1
kind: KubeAegisPolicy
metadata:
  name: allow-frontend-port
spec:
  intentRequest:
    - type: network
      selector:
        cel:
          - labels["app"] == "frontend"
      rule:
        action: Allow
        to:
          - kind: endpoint
            port: "8080"
            labels:
              app: test-ubuntu
            
