apiVersion: cclab.kubeaegis.com/v1
kind: KubeAegisPolicy
metadata:
  name: nginx-port-block
spec:
  intentRequest:
    - type: network
      selector:
        match:
          - kind: Pod
            namespace: default
            matchLabels:
              app: nginx
      rule:
        action: Block
        to:
          - kind: port
            port: "80"
            protocol: TCP
            
