---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cclab.kubeaegis.com
  resources:
  - kubeaegispolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cclab.kubeaegis.com
  resources:
  - kubeaegispolicies/finalizers
  verbs:
  - update
- apiGroups:
  - cclab.kubeaegis.com
  resources:
  - kubeaegispolicies/status
  verbs:
  - get
  - patch
  - update
