// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/grpc/kubeaegis.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 메시지 정의
type PolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyName      string `protobuf:"bytes,1,opt,name=policyName,proto3" json:"policyName,omitempty"`           // 정책 이름
	PolicyNamespace string `protobuf:"bytes,2,opt,name=policyNamespace,proto3" json:"policyNamespace,omitempty"` // 정책 네임스페이스
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_kubeaegis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_kubeaegis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_kubeaegis_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyRequest) GetPolicyNamespace() string {
	if x != nil {
		return x.PolicyNamespace
	}
	return ""
}

type PolicyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success           bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                     // 성공/실패 메시지
	AdapterPolicyName string `protobuf:"bytes,3,opt,name=adapterPolicyName,proto3" json:"adapterPolicyName,omitempty"` // 실제 적용된 정책 이름
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_kubeaegis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_kubeaegis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_kubeaegis_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PolicyResponse) GetAdapterPolicyName() string {
	if x != nil {
		return x.AdapterPolicyName
	}
	return ""
}

type PolicyDeletionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyName      string   `protobuf:"bytes,1,opt,name=policyName,proto3" json:"policyName,omitempty"`           // 정책 이름
	PolicyNamespace string   `protobuf:"bytes,2,opt,name=policyNamespace,proto3" json:"policyNamespace,omitempty"` // 정책 네임스페이스
	KspNames        []string `protobuf:"bytes,3,rep,name=kspNames,proto3" json:"kspNames,omitempty"`               // 삭제된 KSP 이름 목록
}

func (x *PolicyDeletionRequest) Reset() {
	*x = PolicyDeletionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_kubeaegis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDeletionRequest) ProtoMessage() {}

func (x *PolicyDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_kubeaegis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDeletionRequest.ProtoReflect.Descriptor instead.
func (*PolicyDeletionRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_kubeaegis_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyDeletionRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyDeletionRequest) GetPolicyNamespace() string {
	if x != nil {
		return x.PolicyNamespace
	}
	return ""
}

func (x *PolicyDeletionRequest) GetKspNames() []string {
	if x != nil {
		return x.KspNames
	}
	return nil
}

type PolicyDeletionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 성공/실패 메시지
}

func (x *PolicyDeletionResponse) Reset() {
	*x = PolicyDeletionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_kubeaegis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDeletionResponse) ProtoMessage() {}

func (x *PolicyDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_kubeaegis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDeletionResponse.ProtoReflect.Descriptor instead.
func (*PolicyDeletionResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_kubeaegis_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyDeletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PolicyDeletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_grpc_kubeaegis_proto protoreflect.FileDescriptor

var file_api_grpc_kubeaegis_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x61,
	0x65, 0x67, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x75, 0x62, 0x65,
	0x61, 0x65, 0x67, 0x69, 0x73, 0x22, 0x59, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x72, 0x0a, 0x0e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x15, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a,
	0x0f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x73, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x73, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xb7, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x65, 0x67, 0x69,
	0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x65, 0x67, 0x69, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x14,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x65, 0x67, 0x69, 0x73,
	0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x61, 0x65, 0x67,
	0x69, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x63, 0x6c, 0x61, 0x62, 0x2d,
	0x69, 0x6e, 0x75, 0x2f, 0x4b, 0x75, 0x62, 0x65, 0x41, 0x65, 0x67, 0x69, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_kubeaegis_proto_rawDescOnce sync.Once
	file_api_grpc_kubeaegis_proto_rawDescData = file_api_grpc_kubeaegis_proto_rawDesc
)

func file_api_grpc_kubeaegis_proto_rawDescGZIP() []byte {
	file_api_grpc_kubeaegis_proto_rawDescOnce.Do(func() {
		file_api_grpc_kubeaegis_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_kubeaegis_proto_rawDescData)
	})
	return file_api_grpc_kubeaegis_proto_rawDescData
}

var file_api_grpc_kubeaegis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_kubeaegis_proto_goTypes = []interface{}{
	(*PolicyRequest)(nil),          // 0: kubeaegis.PolicyRequest
	(*PolicyResponse)(nil),         // 1: kubeaegis.PolicyResponse
	(*PolicyDeletionRequest)(nil),  // 2: kubeaegis.PolicyDeletionRequest
	(*PolicyDeletionResponse)(nil), // 3: kubeaegis.PolicyDeletionResponse
}
var file_api_grpc_kubeaegis_proto_depIdxs = []int32{
	0, // 0: kubeaegis.PolicyService.DispatchPolicy:input_type -> kubeaegis.PolicyRequest
	2, // 1: kubeaegis.PolicyService.NotifyPolicyDeletion:input_type -> kubeaegis.PolicyDeletionRequest
	1, // 2: kubeaegis.PolicyService.DispatchPolicy:output_type -> kubeaegis.PolicyResponse
	3, // 3: kubeaegis.PolicyService.NotifyPolicyDeletion:output_type -> kubeaegis.PolicyDeletionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_kubeaegis_proto_init() }
func file_api_grpc_kubeaegis_proto_init() {
	if File_api_grpc_kubeaegis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_kubeaegis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_kubeaegis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_kubeaegis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyDeletionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_kubeaegis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyDeletionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_kubeaegis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_kubeaegis_proto_goTypes,
		DependencyIndexes: file_api_grpc_kubeaegis_proto_depIdxs,
		MessageInfos:      file_api_grpc_kubeaegis_proto_msgTypes,
	}.Build()
	File_api_grpc_kubeaegis_proto = out.File
	file_api_grpc_kubeaegis_proto_rawDesc = nil
	file_api_grpc_kubeaegis_proto_goTypes = nil
	file_api_grpc_kubeaegis_proto_depIdxs = nil
}
